name: Terraform Change PR Commenter v2
description: Parse changes from Terraform Plan JSON and post them for PR review
branding:
  icon: "git-pull-request"
  color: "green"
inputs:
  json-file:
    description: File location for the Terraform Plan JSON file
    required: false
    default: tfplan.json
  github-token:
    description: GitHub Token
    required: false
    default: "${{github.token}}"
  expand-comment:
    description: If true, expand the details comment by default
    required: false
    default: "false"
  include-plan-job-summary:
    description: If true, add the results of the plan to the workflow job summary
    required: false
    default: "false"
  header-file:
    description: Filename for header content
    required: false
    default: "act-tmp-header.txt"
  footer-file:
    description: File name for footer content
    required: false
    default: "act-tmp-footer.txt"
  include-workflow-link:
    description: If true, include a link to the workflow in the comment
    required: false
    default: false
  quiet:
    description: Skips the comment if there are no changes
    required: false
    default: false
runs:
  using: node20
  main: dist/index.js
